-- MySQL Script generated by MySQL Workbench
-- dom 23 fev 2020 12:56:21 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tap` DEFAULT CHARACTER SET utf8 ;
USE `tap` ;

-- -----------------------------------------------------
-- Table `tap`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `type` ENUM('user', 'adm') NOT NULL DEFAULT 'user',
  `is_logged` TINYINT(1) NULL,
  `auth` VARCHAR(45) NULL,
  `dthr_request_recovery_pw` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `height` DECIMAL(3,2) NULL,
  `weight` DECIMAL(6,3) NULL,
  `gender` ENUM('m', 'f') NULL,
  `dt_birth` DATE NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `tap`.`action_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`action_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `type` ENUM('financial', 'task') NOT NULL,
  `description` TINYTEXT NULL,
  `value` DECIMAL(10,2) NULL,
  `dt_initial` DATE NULL,
  `dt_final` DATE NULL,
  `is_public` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_task_type_UNIQUE` (`name` ASC),
  INDEX `fk_action_type_user1_idx` (`user` ASC),
  CONSTRAINT `fk_action_type_user1`
    FOREIGN KEY (`user`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tap`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`action` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL,
  `action_type` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TINYTEXT NULL,
  `active` ENUM('0', '1') NOT NULL,
  `indice` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `ic_repeats` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0 = se a atividade nao é repetitiva\n1= se a atividade é repetitiva (tomar remedio, fazer exercicios, etc)',
  `active_days` VARCHAR(255) NULL,
  `active_hours` VARCHAR(255) NULL COMMENT 'intervalo que a atividade se repete, se for repetitiva\n',
  `dthr_initial` DATETIME NULL,
  `dthr_final` DATETIME NULL,
  `value` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_user1_idx` (`user` ASC),
  INDEX `fk_task_task_type1_idx` (`action_type` ASC),
  CONSTRAINT `fk_task_user1`
    FOREIGN KEY (`user`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_task_type1`
    FOREIGN KEY (`action_type`)
    REFERENCES `tap`.`action_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tap`.`take_care_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`take_care_of` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `caregiver` INT UNSIGNED NOT NULL,
  `supervised` INT UNSIGNED NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial_project` ENUM('0', '1') NOT NULL DEFAULT '0',
  `task` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_take_care_of_user1_idx` (`caregiver` ASC),
  INDEX `fk_take_care_of_user2_idx` (`supervised` ASC),
  CONSTRAINT `fk_take_care_of_user1`
    FOREIGN KEY (`caregiver`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_take_care_of_user2`
    FOREIGN KEY (`supervised`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tap`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`email` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tittle` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`tittle` ASC));


-- -----------------------------------------------------
-- Table `tap`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`config` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
