-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 19:57:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tap` DEFAULT CHARACTER SET utf8 ;
USE `tap` ;

-- -----------------------------------------------------
-- Table `tap`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `type` ENUM('user', 'adm') NOT NULL DEFAULT 'user',
  `is_logged` TINYINT(1) NULL DEFAULT NULL,
  `auth` VARCHAR(45) NULL DEFAULT NULL,
  `dthr_request_recovery_pw` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `height` DECIMAL(3,2) NULL DEFAULT NULL,
  `weight` DECIMAL(6,3) NULL DEFAULT NULL,
  `gender` ENUM('m', 'f') NULL DEFAULT NULL,
  `dt_birth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tap`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `type` ENUM('financial', 'task') NOT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `value` DECIMAL(10,2) NULL DEFAULT NULL,
  `dt_initial` DATE NULL DEFAULT NULL,
  `dt_final` DATE NULL DEFAULT NULL,
  `is_public` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`, `user`),
  INDEX `fk_category_user_idx` (`user` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tap`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`action` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT(10) UNSIGNED NOT NULL,
  `category` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `active` ENUM('0', '1') NOT NULL,
  `indice` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `repeats` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0 = se a atividade nao é repetitiva1= se a atividade é repetitiva (tomar remedio, fazer exercicios, etc)',
  `active_days` VARCHAR(255) NULL DEFAULT NULL,
  `active_hours` VARCHAR(255) NULL DEFAULT NULL COMMENT 'intervalo que a atividade se repete, se for repetitiva\\n',
  `dthr_initial` DATETIME NULL DEFAULT NULL,
  `dthr_final` DATETIME NULL DEFAULT NULL,
  `value` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user`, `category`),
  INDEX `fk_action_user1_idx` (`user` ASC) VISIBLE,
  INDEX `fk_action_category1_idx` (`category` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tap`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`config` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tap`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`email` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tittle` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`tittle` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tap`.`take_care_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tap`.`take_care_of` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `caregiver` INT(10) UNSIGNED NOT NULL,
  `supervised` INT(10) UNSIGNED NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial_project` ENUM('0', '1') NOT NULL DEFAULT '0',
  `task` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`, `caregiver`, `supervised`),
  INDEX `fk_take_care_of_user1_idx1` (`caregiver` ASC) VISIBLE,
  INDEX `fk_take_care_of_user2_idx1` (`supervised` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
