-- MySQL Script generated by MySQL Workbench
-- sex 31 jan 2020 10:09:54 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jdc_tap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jdc_tap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jdc_tap` DEFAULT CHARACTER SET utf8 ;
USE `jdc_tap` ;

-- -----------------------------------------------------
-- Table `jdc_tap`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `type` ENUM('user', 'adm') NOT NULL DEFAULT 'user',
  `auth` VARCHAR(45) NULL,
  `cd_recovery_pw` VARCHAR(90) NULL,
  `dthr_request_recovery_pw` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `height` DECIMAL(6,3) NULL,
  `weight` DECIMAL(3,2) NULL,
  `gender` ENUM('m', 'f') NULL,
  `dt_birth` DATE NULL,
  `menu_config` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cd_auth_UNIQUE` (`auth` ASC),
  UNIQUE INDEX `cd_recovery_pw_UNIQUE` (`cd_recovery_pw` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdc_tap`.`task_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`task_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_task_type_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdc_tap`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL,
  `task_type` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` ENUM('0', '1') NOT NULL,
  `indice` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `ic_repeats` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0 = se a atividade nao é repetitiva\n1= se a atividade é repetitiva (tomar remedio, fazer exercicios, etc)',
  `active_days` VARCHAR(255) NULL,
  `active_hours` VARCHAR(255) NULL COMMENT 'intervalo que a atividade se repete, se for repetitiva\n',
  `dt_final` DATE NULL,
  `hr_final` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_user1_idx` (`user` ASC),
  INDEX `fk_task_task_type1_idx` (`task_type` ASC),
  CONSTRAINT `fk_task_user1`
    FOREIGN KEY (`user`)
    REFERENCES `jdc_tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_task_type1`
    FOREIGN KEY (`task_type`)
    REFERENCES `jdc_tap`.`task_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdc_tap`.`movement_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`movement_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_movement_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdc_tap`.`financial_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`financial_project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `value` DECIMAL(10,2) UNSIGNED NOT NULL,
  `dt_initial` DATE NULL,
  `dt_final` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_financial_project_user1_idx` (`user` ASC),
  CONSTRAINT `fk_financial_project_user1`
    FOREIGN KEY (`user`)
    REFERENCES `jdc_tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdc_tap`.`financial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`financial` (
  `id` INT UNSIGNED NOT NULL,
  `user` INT UNSIGNED NOT NULL,
  `movement_type` INT UNSIGNED NOT NULL,
  `financial_project` INT UNSIGNED NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `type` ENUM('in', 'out') NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  INDEX `fk_financial_user1_idx` (`user` ASC),
  INDEX `fk_financial_moviment_type1_idx` (`movement_type` ASC),
  INDEX `fk_financial_financial_project1_idx` (`financial_project` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_financial_user1`
    FOREIGN KEY (`user`)
    REFERENCES `jdc_tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financial_moviment_type1`
    FOREIGN KEY (`movement_type`)
    REFERENCES `jdc_tap`.`movement_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financial_financial_project1`
    FOREIGN KEY (`financial_project`)
    REFERENCES `jdc_tap`.`financial_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdc_tap`.`take_care_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jdc_tap`.`take_care_of` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `caregiver` INT UNSIGNED NOT NULL,
  `supervised` INT UNSIGNED NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial_project` ENUM('0', '1') NOT NULL DEFAULT '0',
  `task` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_take_care_of_user1_idx` (`caregiver` ASC),
  INDEX `fk_take_care_of_user2_idx` (`supervised` ASC),
  CONSTRAINT `fk_take_care_of_user1`
    FOREIGN KEY (`caregiver`)
    REFERENCES `jdc_tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_take_care_of_user2`
    FOREIGN KEY (`supervised`)
    REFERENCES `jdc_tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
