-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 12:40:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tap
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tap` ;

-- -----------------------------------------------------
-- Schema tap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tap` DEFAULT CHARACTER SET utf8 ;
USE `tap` ;

-- -----------------------------------------------------
-- Table `tap`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`user` ;

CREATE TABLE IF NOT EXISTS `tap`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `type` ENUM('user', 'adm') NOT NULL DEFAULT 'user',
  `auth` VARCHAR(45) NULL,
  `cd_recovery_pw` VARCHAR(90) NULL,
  `dthr_recovery_pw_request` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `height` DECIMAL(6,3) NULL,
  `weight` DECIMAL(3,2) NULL,
  `gender` ENUM('m', 'f') NULL,
  `dt_birth` DATE NULL,
  `menu_config` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `cd_auth_UNIQUE` (`auth` ASC) ,
  UNIQUE INDEX `cd_recovery_pw_UNIQUE` (`cd_recovery_pw` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap`.`task_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`task_type` ;

CREATE TABLE IF NOT EXISTS `tap`.`task_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_task_type_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`task` ;

CREATE TABLE IF NOT EXISTS `tap`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `task_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` ENUM('0', '1') NOT NULL,
  `indice` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `ic_repeats` ENUM('0', '1') NULL DEFAULT '0',
  `active_days` VARCHAR(255) NULL,
  `active_hours` VARCHAR(255) NULL COMMENT 'intervalo que a atividade se repete, se for repetitiva\n',
  `dt_final` DATE NULL,
  `hr_final` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_user1_idx` (`user` ASC) ,
  INDEX `fk_task_task_type1_idx` (`task_type` ASC) ,
  CONSTRAINT `fk_task_user1`
    FOREIGN KEY (`user`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_task_type1`
    FOREIGN KEY (`task_type`)
    REFERENCES `tap`.`task_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap`.`moviment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`moviment_type` ;

CREATE TABLE IF NOT EXISTS `tap`.`moviment_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nm_movement_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap`.`financial_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`financial_project` ;

CREATE TABLE IF NOT EXISTS `tap`.`financial_project` (
  `financial_project` INT NOT NULL,
  `user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `value` DECIMAL(10,2) UNSIGNED NOT NULL,
  `dt_initial` DATE NULL,
  `dt_final` DATE NOT NULL,
  PRIMARY KEY (`financial_project`),
  INDEX `fk_financial_project_user1_idx` (`user` ASC) ,
  CONSTRAINT `fk_financial_project_user1`
    FOREIGN KEY (`user`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap`.`financial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`financial` ;

CREATE TABLE IF NOT EXISTS `tap`.`financial` (
  `id` VARCHAR(45) NOT NULL,
  `user` INT NOT NULL,
  `movement_type` INT NOT NULL,
  `financial_project` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `type` ENUM('in', 'out') NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  INDEX `fk_financial_user1_idx` (`user` ASC) ,
  INDEX `fk_financial_moviment_type1_idx` (`movement_type` ASC) ,
  INDEX `fk_financial_financial_project1_idx` (`financial_project` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_financial_user1`
    FOREIGN KEY (`user`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financial_moviment_type1`
    FOREIGN KEY (`movement_type`)
    REFERENCES `tap`.`moviment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financial_financial_project1`
    FOREIGN KEY (`financial_project`)
    REFERENCES `tap`.`financial_project` (`financial_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap`.`take_care_of`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap`.`take_care_of` ;

CREATE TABLE IF NOT EXISTS `tap`.`take_care_of` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caregiver` INT NOT NULL,
  `supervised` INT NOT NULL,
  `active` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial` ENUM('0', '1') NOT NULL DEFAULT '0',
  `financial_project` ENUM('0', '1') NOT NULL DEFAULT '0',
  `task` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_take_care_of_user1_idx` (`caregiver` ASC) ,
  INDEX `fk_take_care_of_user2_idx` (`supervised` ASC) ,
  CONSTRAINT `fk_take_care_of_user1`
    FOREIGN KEY (`caregiver`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_take_care_of_user2`
    FOREIGN KEY (`supervised`)
    REFERENCES `tap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
